In [71]:
import numpy as np
arr1D = np.arange(10)
print(arr1D)

[0 1 2 3 4 5 6 7 8 9]


In [81]:
# Reshaping our array
arr2D = np.arange(16).reshape(4,4)
print(arr2D)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [82]:
# Finding the shape, data type and stride of arr
shape = arr2D.shape
data_type = arr2D.dtype
stride = arr2D.strides

print(f"Shape: {shape}, Data_type: {data_type}, Stride: {stride}",)

Shape: (4, 4), Data_type: int32, Stride: (16, 4)


###### Here is tells us that we have to move 4 bytes to move from one element its adjacent in the same row and 20 bytes to move from one row to the its adjacent in the same col.

In [83]:
# Converting a list to array
li = [[1,2,3,5],[6,7,8,9]]
li = np.array(li)

In [84]:
# Simple broadcasting to the array
li += 5
print(li)

[[ 6  7  8 10]
 [11 12 13 14]]


In [85]:
# Equally divides the number betwenn start and stop
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
# Shallow copy

original = [[1, 2, 3]]
shallow = original.copy()

# Modifying the shallow copy
shallow[0][0] = 100
print(shallow)  # [100, 2, 3]
print(original)  # [100, 2, 3]

# Modifying the original
original[0][1] = 200
print(shallow)  # [100, 200, 3]
print(original)  # [1, 200, 3]

[[100, 2, 3]]
[[100, 2, 3]]
[[100, 200, 3]]
[[100, 200, 3]]


In [88]:
# Linear algebra functions example

arr3 = np.array([[1,2],[3,4]])
arr3_inv = np.linalg.inv(arr3)
print(f"Inverse of \n{arr3}: \n{arr3_inv}")

arr4 = np.linalg.det(arr3)
print(f"Determinant of array is \n{arr4}")

Inverse of 
[[1 2]
 [3 4]]: 
[[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of array is 
-2.0000000000000004


In [89]:
# To flatten an array
Flattend_array = arr2D.flatten()
print(Flattend_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [90]:
# Flipping an array
# For 1D
print(Flattend_array[::-1])

# For all Dimensions
print(np.flip(Flattend_array))

# For 2D we have other functions like np.flipudp and np.fliplr

[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [91]:
# Slicing works like array[row_start:row_stop:row_step, col_start:col_stop:col_step

Flattend_array[1:7:2]

array([1, 3, 5])

In [95]:
# Mean, median, std
Flattend_array_mean = np.mean(Flattend_array)
Flattend_array_median = np.median(Flattend_array)
Flattend_array_std = np.std(Flattend_array)
Flattend_array_var = np.var(Flattend_array)

print(f"For array {Flattend_array} below are various stats")
print(f"Mean : {Flattend_array_mean}")
print(f"Median : {Flattend_array_median}")
print(f"Standard Deviation: {Flattend_array_std}")
print(f"Variance: {Flattend_array_var}")

# Mode is not present in numpy

For array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] below are various stats
Mean : 7.5
Median : 7.5
Standard Deviation: 4.6097722286464435
Variance: 21.25


In [ ]:
# Generate random number
print(np.random.rand(4,3)) # Generates a random array for the specified dimention
np.random.randint(442,535,size=4)

[[0.77383585 0.25260631 0.64613429]
 [0.39328269 0.50026015 0.82195732]
 [0.24609682 0.85206968 0.27014455]
 [0.84389272 0.14399655 0.03476544]]


array([485, 456, 451, 466])

In [107]:
# Percentiles
np.percentile(Flattend_array,[4,5,6]) # Here we can specify quartile too like[4,5,6]

array([0.6 , 0.75, 0.9 ])

21.25
21.25
