In [165]:
# Using Arange
import numpy as np
arr1D = np.arange(10)
print(arr1D)

[0 1 2 3 4 5 6 7 8 9]


In [113]:
# Reshaping our array
arr2D = np.arange(16).reshape(4,4)
print(arr2D)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [114]:
# Finding the shape, data type and stride of arr
shape = arr2D.shape
data_type = arr2D.dtype
stride = arr2D.strides

print(f"Shape: {shape}, Data_type: {data_type}, Stride: {stride}",)

Shape: (4, 4), Data_type: int32, Stride: (16, 4)


##### Here is tells us that we have to move 4 bytes to move from one element its adjacent in the same row and 20 bytes to move from one row to the its adjacent in the same col.

In [115]:
# Converting a list to array
li = [[1,2,3,5],[6,7,8,9]]
li = np.array(li)

In [116]:
# Simple broadcasting to the array
li += 5
print(li)

[[ 6  7  8 10]
 [11 12 13 14]]


In [141]:
# Equally divides the number betwenn start and stop
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [118]:
# Shallow copy

original = [[1, 2, 3]]
shallow = original.copy()

# Modifying the shallow copy
shallow[0][0] = 100
print(shallow)  # [100, 2, 3]
print(original)  # [100, 2, 3]

# Modifying the original
original[0][1] = 200
print(shallow)  # [100, 200, 3]
print(original)  # [1, 200, 3]

[[100, 2, 3]]
[[100, 2, 3]]
[[100, 200, 3]]
[[100, 200, 3]]


In [119]:
# Linear algebra functions example

arr3 = np.array([[1,2],[3,4]])
arr3_inv = np.linalg.inv(arr3)
print(f"Inverse of \n{arr3}: \n{arr3_inv}")

arr4 = np.linalg.det(arr3)
print(f"Determinant of array is \n{arr4}")

Inverse of 
[[1 2]
 [3 4]]: 
[[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of array is 
-2.0000000000000004


In [120]:
# To flatten an array
Flattend_array = arr2D.flatten()
print(Flattend_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [121]:
# Flipping an array
# For 1D
print(Flattend_array[::-1])

# For all Dimensions
print(np.flip(Flattend_array))

# For 2D we have other functions like np.flipudp and np.fliplr

[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [ ]:
# Slicing works like array[row_start:row_stop:row_step, col_start:col_stop:col_step]

Flattend_array[1:7:2]

array([1, 3, 5])

In [123]:
# Mean, median, std
Flattend_array_mean = np.mean(Flattend_array)
Flattend_array_median = np.median(Flattend_array)
Flattend_array_std = np.std(Flattend_array)
Flattend_array_var = np.var(Flattend_array)

print(f"For array {Flattend_array} below are various stats")
print(f"Mean : {Flattend_array_mean}")
print(f"Median : {Flattend_array_median}")
print(f"Standard Deviation: {Flattend_array_std}")
print(f"Variance: {Flattend_array_var}")

# Mode is not present in numpy

For array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] below are various stats
Mean : 7.5
Median : 7.5
Standard Deviation: 4.6097722286464435
Variance: 21.25


In [166]:
# Generate random number
# np.random.rand generates number between 0 and 1

print(np.random.rand(4,3)) # Generates a random array for the specified dimention
np.random.randint(442,535,size=4)

[[0.42637443 0.6449223  0.48596202]
 [0.36859408 0.29005048 0.96431425]
 [0.18263975 0.59333761 0.09822551]
 [0.60195195 0.76309615 0.7442302 ]]


array([465, 453, 479, 474])

In [167]:
# Percentiles
np.percentile(Flattend_array,67) # Here we can specify quartile too like[4,5,6]

10.05

In [131]:
#Creating array of 2X4 filles with 0
arr = np.zeros((2,4))
type(arr[0][0])

numpy.float64

In [154]:
# Multiplication
arr = np.array([[56,65,6],[9,9,9]])
arr2 = np.array([[6,5,68]])
np.multiply(arr,arr2)

array([[336, 325, 408],
       [ 54,  45, 612]])

In [168]:
# To apply a fucntion along row and col
def fun(x):
    return x[0]+x[1]+x[2]
np.apply_along_axis(fun,1,arr)

array([127,  27])

In [ ]:
# To apply a funtion to all elements of an array
def add_2(x):
    return x if x<10 else x**9
func = np.vectorize(add_2)
func(np.array([[1,2,4],[4,5,9]]))

array([[1, 2, 4],
       [4, 5, 9]])